# Kommentoi, kun issue on suljettu
name: Comment issues when closed 
on: 
  issues:
    types:
      - closed
jobs: 
  label_issues: 
    runs-on: ubuntu-latest 
    permissions: 
      issues: write
    steps: 
      - name: Comment on closed issue 
        uses: peter-evans/create-or-update-comment@v1 
        with:
          issue-number: ${{ github.event.issue.number }} 
          body: | 
           Thanks for CLOSING this issue!
