# Kommentoi, kun k채ytt채j채 avaa ensimm채isen pull requestin
name: Greet when a user opens first Request 
on: 
  pull_request:
    types: opened
    
jobs: 
  greeting: 
    runs-on: ubuntu-latest 
    permissions: 
      pull-requests: write
    steps: 
    - uses: actions/first-interaction@v1 
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }} 
        pr-message: "Thanks for the first Pull Request"
